# Джем MyIndie LVL 9

# 0. Подготовка

In [ ]:
import os
from datetime import datetime
# from pathlib import Path
# import shutil
import json
import requests
import re
import pandas as pd
import numpy as np


# Константы
MYINDIE_JAM_URL = "https://myindie.ru/jams/jam/myindie-game-jam-level-9"
MYINDIE_JAM_URL_PAGES = 3  # Количество страниц с играми на геймджеме
MYINDIE_JAM_SKIP_DOWNLOAD = True
OUTPUT_DIR = "output/"
CRITERIAS = ["art", "sound", "theme", "gameplay", "narrative", "overall_impression"]  # Список критериев для анализа

# Директория для html-файлов джема
jam_path = MYINDIE_JAM_URL.split('/')[-1]  # получаем имя джема вроде "myindie-game-jam-level-9"
if jam_path is None or jam_path == "":
    raise ValueError("Не удалось извлечь путь джема из URL. Проверьте правильность MYINDIE_JAM_URL.")
os.makedirs(os.path.join(OUTPUT_DIR, jam_path), exist_ok=True)

pd.set_option('display.float_format', '{:.3f}'.format)
pd.set_option('display.max_rows', None)


def get_jam_games_urls(jam_url):
    """ Скачивает страницу списка игр джема и извлекает URL игр. """

    response = requests.get(jam_url)

    if response.status_code != 200:
        print(f"Ошибка при получении страницы джема: `{response.status_code}`")
        return []

    games_urls = re.findall(r'/games/game/[\w-]+', response.text)
    games_urls = [f"https://myindie.ru{url}" for url in games_urls]
    print(f"Найдено {len(games_urls)} URL игр в: {jam_url}")

    return games_urls


def unflatten_nuxt_data(data):
    """ Разворачивает плоскую структуру данных Nuxt.js в дерево. """
    if not isinstance(data, list) or not data: return data
    memo = {}
    def resolve(val):
        if isinstance(val, int) and 0 <= val < len(data):
            if val not in memo:
                memo[val] = resolve_item(data[val])
            return memo[val]
        return val
    def resolve_item(item):
        if isinstance(item, dict):
            return {k: resolve(v) for k, v in item.items()}
        if isinstance(item, list):
            return [resolve(v) for v in item]
        return item
    return resolve_item(data[1])

# 1. Скачиваем все страницы игр геймджема

1.1 Ищем все игры джема

In [36]:
if not MYINDIE_JAM_SKIP_DOWNLOAD:
    games_urls = []
    for page in range(1, MYINDIE_JAM_URL_PAGES + 1):
        paged_url = f"{MYINDIE_JAM_URL}/games?page={page}"
        print(f"Обрабатываем страницу: {paged_url}")
        urls = get_jam_games_urls(paged_url)
        games_urls.extend(urls)

    print(f"\nНайдено {len(games_urls)} игр на {MYINDIE_JAM_URL_PAGES} страницах:\n{chr(10).join(games_urls)}")

1.2 Скачать все HTML-страницы игр геймджема

In [37]:
if not MYINDIE_JAM_SKIP_DOWNLOAD:
    jam_games_file_path = os.path.join(OUTPUT_DIR, jam_path, f"jam_games.txt")
    if os.path.exists(jam_games_file_path):
        os.remove(jam_games_file_path)
    jam_games_file = open(jam_games_file_path, 'a', encoding='utf-8')

    # DEBUG_GAMES_MAX = 2  # delete
    for i, game_url in enumerate(games_urls): #[:DEBUG_GAMES_MAX]):
        print(f"Обработка URL игры: {game_url}")
        response = requests.get(game_url)
        if response.status_code != 200:
            print(f"* Ошибка при получении страницы игры: `{response.status_code}`")
            continue

        title_match = re.search(r'<title>([^<]+)</title>', response.text)
        if title_match:
            title = f"{i:03d}_" + re.sub(r'[^\w_]', '-', re.sub(r'\s+', '_', title_match.group(1).strip()))
        else:
            title = f"{i:03d}_" + "Unknown"

        output_file_path = os.path.join(OUTPUT_DIR, jam_path, f"{title}.html")
        with open(output_file_path, 'w', encoding='utf-8') as f:
            f.write(response.text)
            print(f"Сохранено в `{output_file_path}`")
        jam_games_file.write(f"{output_file_path} {game_url}\n")

    jam_games_file.close()

# 2. Извлекаем данные со всех страниц игр
2.1 Используем уже скачанные HTML-страницы игр геймджема, чтобы извлечь данные о каждой игре

In [38]:
jam_games_file_path = os.path.join(OUTPUT_DIR, jam_path, "jam_games.txt")
jam_games_file = open(jam_games_file_path, 'r', encoding='utf-8')
print(f"Всего игр в файле `{jam_games_file_path}`: {len(jam_games_file.readlines())}")

Всего игр в файле `output/myindie-game-jam-level-9\jam_games.txt`: 68

2.2 Собираем оценки и отзывы для каждой игры из скачанных файлов

In [ ]:
all_judges_reviews = []  # без разделения по играм
all_participant_reviews = []  # без разделения по играм
all_users_reviews = []  # без разделения по играм
game_reviews = {}  # отзывы для каждой игры, ключ - alias игры, значение - словарь с отзывами по типам

jam_games_file.seek(0)

for line in jam_games_file:
    output_file_path, game_url = line.strip().split(' ', 1)
    alias = game_url.split('/')[-1]
    print(f"Обработка: {game_url}")
    with open(output_file_path, 'r', encoding='utf-8') as f:
        html_content = f.read()

    match = re.search(r'id=\"__NUXT_DATA__\">([^<]+)</script>', html_content)
    if not match:
        print(f"* Не найден __NUXT_DATA__ в `{output_file_path}`\n")
        continue

    json_data = json.loads(match.group(1))
    unflattened = unflatten_nuxt_data(json_data)
    if not unflattened:
        print(f"* Не удалось развернуть данные Nuxt.js в `{output_file_path}`\n")
        continue

    data_section = unflattened.get('data', [])
    if not data_section:
        print(f"* Не найден раздел 'data' в развернутых данных Nuxt.js в `{output_file_path}`\n")
        continue

    # Берем второй элемент списка (индекс 1) — там словарь с результатами
    if isinstance(data_section, list) and len(data_section) > 1:
        payload_container = data_section[1]
        if not payload_container:
            print(f"* Пустой контейнер в `{output_file_path}`\n")
            continue

        # В словаре берем первый ключ (game<alias>)
        if isinstance(payload_container, dict) and payload_container:
            second_key = list(payload_container.keys())[0]
            games = payload_container[second_key]
            if not games:
                print(f"* Пустой объект игры в `{output_file_path}`\n")
                continue

            # Извлекаем отзывы из game_payload['data']['reviews']
            if isinstance(games, dict):
                inner_data = games.get('data', {})
                if not inner_data:
                    print(f"* Пустой объект 'data' в `{output_file_path}`\n")
                    continue

                reviews = inner_data.get('reviews', [])
                if not reviews:
                    print(f"* Не найдено отзывов в `{output_file_path}`\n")
                    continue
                # print(json.dumps(reviews, ensure_ascii=False, indent=2))

                judges = [r for r in reviews if isinstance(r, dict) and r.get('reviewerType') == 'judge' and r.get('user') is not None]
                all_judges_reviews.extend(judges)
                participants = [r for r in reviews if isinstance(r, dict) and r.get('reviewerType') == 'jam-participant' and r.get('user') is not None]
                all_participant_reviews.extend(participants)
                users = [r for r in reviews if isinstance(r, dict) and r.get('reviewerType') == 'user' and r.get('user') is not None]
                all_users_reviews.extend(users)

                game_reviews[alias] = {
                    'judges': judges,
                    'participants': participants,
                    'users': users,
                }
                print(f"Судейских отзывов: {len(judges)} - {', '.join([r.get('user', {}).get('username') for r in judges])}")
                print(f"Отзывы участников: {len(participants)} - {', '.join([r.get('user', {}).get('username') for r in participants])}")
                print(f"Отзывы пользователей: {len(users)} - {', '.join([r.get('user', {}).get('username') for r in users])}\n")

print(f"\nВсего судейских отзывов на джеме: {len(all_judges_reviews)}")
print(f"Всего отзывов участников на джеме: {len(all_participant_reviews)}")
print(f"Всего отзывов пользователей на джеме: {len(all_users_reviews)}")

Обработка: https://myindie.ru/games/game/ultimatum-odna-noch-s-karachunom
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 11 - pafan, SemenLisenko, GhosDist, Ivancorej, KTD, chepuxxx, ArcasHH, Skyline_rozan, Tafari, Crp, CreatorLynx
Отзывы пользователей: 5 - AMONGAS, Waffle, MrGreen, dkotl, tenko

Обработка: https://myindie.ru/games/game/trash-under-ground
Судейских отзывов: 0 -
Отзывы участников: 9 - GhosDist, KTD, ArcasHH, pafan, SemenLisenko, Tafari, GamerGrapes, Skyline_rozan, buZZi6X
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/cult-indie
Судейских отзывов: 4 - DmitriySklyarov, Saley, HelenAllienPoe, PoliKhai
Отзывы участников: 15 - JayxK, phanopera, GhosDist, pafan, Skyline_rozan, Jil, SemenLisenko, peped, Tafari, kafel, epigrodel, BobrikDobrik, Zarya61, KTD, Lacost
Отзывы пользователей: 9 - UnrealQW, Markus_Glevera, ChiFu, GrogShader, eturnercus, ignis, molodoy_venerez, niconikita, Rramad

Обработка: https://myindie.ru/games/game/udivitelnyj-ded
Судейских отзывов: 1 - DmitriySklyarov
Отзывы участников: 12 - GhosDist, pafan, WoltIx, Ivancorej, ArcasHH, Skyline_rozan, Crp, BobrikDobrik, Lacost, buZZi6X, Dionis_369, SemenLisenko
Отзывы пользователей: 3 - UnrealQW, MrGreen, Taburetka

Обработка: https://myindie.ru/games/game/franshiza-ktulhu_nx3
Судейских отзывов: 2 - HelenAllienPoe, PoliKhai
Отзывы участников: 7 - phanopera, KTD, pafan, GamerGrapes, SemenLisenko, Deleted user 33d3f881, buZZi6X
Отзывы пользователей: 1 - GreatPasta

Обработка: https://myindie.ru/games/game/durdom
* Не найдено отзывов в `output/myindie-game-jam-level-9\005_Durdom-_Жанр-_Shooter_-_Инди-игры_-_MyIndie.html`

Обработка: https://myindie.ru/games/game/exorcismo
Судейских отзывов: 0 -
Отзывы участников: 9 - phanopera, pafan, JayxK, Skyline_rozan, SemenLisenko, Tafari, Lacost, Deleted user 33d3f881, Zarya61
Отзывы пользователей: 2 - glhf, liff

Обработка: https://myindie.ru/games/game/5-days-with-the-necronomicon_opw
Судейских отзывов: 3 - Saley, DmitriySklyarov, PoliKhai
Отзывы участников: 7 - phanopera, Skyline_rozan, KTD, SemenLisenko, pafan, JayxK, Heshi
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/full-moon-twin-rite
Судейских отзывов: 0 -
Отзывы участников: 5 - KTD, pafan, SemenLisenko, Tafari, Deleted user 33d3f881
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/zayachij-kult
Судейских отзывов: 3 - PoliKhai, DmitriySklyarov, Saley
Отзывы участников: 14 - phanopera, epigrodel, ArcasHH, pafan, JayxK, GamerGrapes, Lacost, SemenLisenko, peped, Ivancorej, Zarya61, kafel, buZZi6X, KTD
Отзывы пользователей: 4 - UnrealQW, Pompom, liff, Taburetka

Обработка: https://myindie.ru/games/game/no-edward
Судейских отзывов: 4 - DmitriySklyarov, HelenAllienPoe, PoliKhai, Saley
Отзывы участников: 10 - phanopera, epigrodel, dwang, KTD, Skyline_rozan, pafan, Lacost, Pinecom, peped, SemenLisenko
Отзывы пользователей: 1 - UnrealQW

Обработка: https://myindie.ru/games/game/protokol-pentagrammy
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 6 - sasha, pafan, Heshi, SemenLisenko, Trase, KTD
Отзывы пользователей: 4 - Vlad_Borets, BehindThePixels, PurpleGames, whaledevelop

Обработка: https://myindie.ru/games/game/all-hail-sister
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 9 - GhosDist, sasha, SemenLisenko, pafan, WoltIx, Heshi, Pinecom, yurimavt, Zarya61
Отзывы пользователей: 3 - ImmortalSheet, SerikVSerenkih, UnrealQW

Обработка: https://myindie.ru/games/game/s-run_5pm
Судейских отзывов: 0 -
Отзывы участников: 9 - phanopera, KTD, pafan, SemenLisenko, CreatorLynx, ArcasHH, GamerGrapes, Tafari, bolshoj_bob
Отзывы пользователей: 4 - Slashka, eturnercus, ignis, Rramad

Обработка: https://myindie.ru/games/game/les
Судейских отзывов: 3 - Saley, DmitriySklyarov, PoliKhai
Отзывы участников: 10 - JayxK, phanopera, Har_On, pafan, SemenLisenko, Pinecom, Lacost, ArcasHH, yurimavt, Deleted user 33d3f881
Отзывы пользователей: 3 - UnrealQW, Markus_Glevera, ChiFu

Обработка: https://myindie.ru/games/game/curse-of-the-grail
Судейских отзывов: 0 -
Отзывы участников: 8 - JayxK, KTD, GamerGrapes, pafan, SemenLisenko, epigrodel, HenjTV, Pinecom
Отзывы пользователей: 4 - Markus_Glevera, linka, liff, KatrinGame

Обработка: https://myindie.ru/games/game/kul-pustoshi
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 10 - YuraBulba, sasha, Veles, Kosd, Har_On, SemenLisenko, Ivancorej, AlexeySergeevich, BobrikDobrik, buZZi6X
Отзывы пользователей: 1 - liff

Обработка: https://myindie.ru/games/game/bureau-of-accult-affairs_aaq
Судейских отзывов: 0 -
Отзывы участников: 7 - JayxK, Skyline_rozan, ArcasHH, KTD, pafan, SemenLisenko, buZZi6X
Отзывы пользователей: 1 - tenko

Обработка: https://myindie.ru/games/game/cultfire
Судейских отзывов: 0 -
Отзывы участников: 8 - sasha, KTD, pafan, Ivancorej, SemenLisenko, Tafari, buZZi6X, Deleted user 33d3f881
Отзывы пользователей: 1 - liff

Обработка: https://myindie.ru/games/game/occulte
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 7 - phanopera, KTD, pafan, Lacost, Jil, SemenLisenko, Zarya61
Отзывы пользователей: 2 - Farshik52, Paulseagull

Обработка: https://myindie.ru/games/game/eyesless
Судейских отзывов: 0 -
Отзывы участников: 9 - sasha, KTD, SemenLisenko, pafan, Ivancorej, GamerGrapes, Heshi, Lacost, CreatorLynx
Отзывы пользователей: 1 - ImmortalSheet

Обработка: https://myindie.ru/games/game/mrachnyj-obet
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 5 - KTD, pafan, SemenLisenko, Tafari, kafel
Отзывы пользователей: 2 - liff, s123DoH

Обработка: https://myindie.ru/games/game/oculus-ritual
Судейских отзывов: 0 -
Отзывы участников: 8 - sasha, GhosDist, BobrikDobrik, Skyline_rozan, SemenLisenko, GamerGrapes, pafan, Tafari
Отзывы пользователей: 1 - liff

Обработка: https://myindie.ru/games/game/deal-with-the-demon
Судейских отзывов: 3 - DmitriySklyarov, PoliKhai, Saley
Отзывы участников: 6 - ArcasHH, JayxK, KTD, SemenLisenko, pafan, buZZi6X
Отзывы пользователей: 2 - Mr.Johny, Markus_Glevera

Обработка: https://myindie.ru/games/game/rybolovnyj-kult
Судейских отзывов: 4 - PoliKhai, HelenAllienPoe, Saley, DmitriySklyarov
Отзывы участников: 14 - JayxK, sasha, Har_On, ArcasHH, pafan, Skyline_rozan, WoltIx, peped, SemenLisenko, kafel, Heshi, Zarya61, Bogila, KTD
Отзывы пользователей: 4 - glhf, jikantao, SoSiSkA, Farshik52

Обработка: https://myindie.ru/games/game/cult-of-the-deep-dungeon
Судейских отзывов: 0 -
Отзывы участников: 6 - GhosDist, ArcasHH, SemenLisenko, pafan, Heshi, CreatorLynx
Отзывы пользователей: 1 - SerikVSerenkih

Обработка: https://myindie.ru/games/game/trust-us_7ak
Судейских отзывов: 4 - DmitriySklyarov, Saley, PoliKhai, HelenAllienPoe
Отзывы участников: 18 - JayxK, phanopera, Har_On, KTD, dwang, epigrodel, sasha, ArcasHH, pafan, Skyline_rozan, SemenLisenko, peped, Lacost, Ivancorej, Zarya61, AndreyFish, kafel, buZZi6X
Отзывы пользователей: 1 - whaledevelop

Обработка: https://myindie.ru/games/game/chernobot
Судейских отзывов: 4 - PoliKhai, HelenAllienPoe, Saley, DmitriySklyarov
Отзывы участников: 6 - sasha, pafan, Lacost, SemenLisenko, Deleted user 33d3f881, KTD
Отзывы пользователей: 6 - Victor, anze4l, TvoyaMama, dodo, Rramad, tenko

Обработка: https://myindie.ru/games/game/grimoire-of-the-void_flm
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 6 - KTD, Lacost, ArcasHH, pafan, Jil, SemenLisenko
Отзывы пользователей: 5 - liff, pupupiruru, jikantao, SoSiSkA, Rramad

Обработка: https://myindie.ru/games/game/the-philosophers-stone
Судейских отзывов: 0 -
Отзывы участников: 7 - YuraBulba, JayxK, KTD, SemenLisenko, GhosDist, pafan, Deleted user 33d3f881
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/die-my-darling_nzc
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 10 - JayxK, Har_On, pafan, Trase, NaLLsuR, peped, Zarya61, buZZi6X, Lacost, SemenLisenko
Отзывы пользователей: 2 - MrGreen, jikantao

Обработка: https://myindie.ru/games/game/pikovaya-dama-ritual-izgnaniya
Судейских отзывов: 3 - DmitriySklyarov, PoliKhai, Saley
Отзывы участников: 9 - phanopera, JayxK, BobrikDobrik, pafan, SemenLisenko, KTD, GamerGrapes, kafel, Zarya61
Отзывы пользователей: 13 - Renat, Yukina, SMS, glhf, ignis, Tanya, s123DoH, kurukatto, Mentozavr, twinki, Farshik52, dkotl, LerekerUseless

Обработка: https://myindie.ru/games/game/crossswitch
Судейских отзывов: 0 -
Отзывы участников: 7 - sasha, GhosDist, KTD, pafan, Tafari, SemenLisenko, Pinecom
Отзывы пользователей: 1 - Rramad

Обработка: https://myindie.ru/games/game/tajna-alistera
Судейских отзывов: 0 -
Отзывы участников: 7 - KTD, pafan, NaLLsuR, Lacost, GamerGrapes, Tafari, SemenLisenko
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/seer-for-hire_q3c
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 7 - GhosDist, ArcasHH, KTD, SemenLisenko, pafan, peped, buZZi6X
Отзывы пользователей: 3 - ignis, jikantao, Rramad

Обработка: https://myindie.ru/games/game/neofit
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 10 - JayxK, ArcasHH, KTD, pafan, Trase, epigrodel, AlexeySergeevich, Skyline_rozan, SemenLisenko, Bogila
Отзывы пользователей: 5 - gugugaga, liff, eturnercus, mclovin, Rramad

Обработка: https://myindie.ru/games/game/the-second-chance-agency
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 3 - SemenLisenko, pafan, KTD
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/godeath
Судейских отзывов: 0 -
Отзывы участников: 9 - JayxK, Har_On, KTD, pafan, Skyline_rozan, GamerGrapes, YuraBulba, Pinecom, SemenLisenko
Отзывы пользователей: 1 - liff

Обработка: https://myindie.ru/games/game/ravings
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 6 - GhosDist, KTD, pafan, Ivancorej, NaLLsuR, SemenLisenko
Отзывы пользователей: 1 - tenko

Обработка: https://myindie.ru/games/game/okkylt
Судейских отзывов: 0 -
Отзывы участников: 4 - ArcasHH, pafan, CreatorLynx, SemenLisenko
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/cultist-run
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 10 - ArcasHH, sasha, Skyline_rozan, GhosDist, pafan, peped, SemenLisenko, Heshi, buZZi6X, Zarya61
Отзывы пользователей: 8 - ignis, PurpleGames, UnrealQW, ImmortalSheet, SerikVSerenkih, glhf, dablyouu, SoSiSkA

Обработка: https://myindie.ru/games/game/cult-wars
Судейских отзывов: 0 -
Отзывы участников: 9 - GhosDist, sasha, KTD, pafan, Heshi, Zarya61, buZZi6X, SemenLisenko, Dionis_369
Отзывы пользователей: 2 - UnrealQW, tenko

Обработка: https://myindie.ru/games/game/a-seance
Судейских отзывов: 3 - Saley, DmitriySklyarov, PoliKhai
Отзывы участников: 7 - pafan, NaLLsuR, JantayBerikbaev, Ivancorej, Tafari, Dionis_369, SemenLisenko
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/cold-saratov
Судейских отзывов: 3 - Saley, PoliKhai, DmitriySklyarov
Отзывы участников: 11 - phanopera, epigrodel, ArcasHH, dwang, sasha, pafan, GamerGrapes, BobrikDobrik, Pinecom, buZZi6X, SemenLisenko
Отзывы пользователей: 3 - UnrealQW, Rramad, LerekerUseless

Обработка: https://myindie.ru/games/game/gutsout
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 11 - epigrodel, JayxK, phanopera, Har_On, Skyline_rozan, pafan, BobrikDobrik, GamerGrapes, Tafari, SemenLisenko, buZZi6X
Отзывы пользователей: 3 - MrGreen, ignis, dkotl

Обработка: https://myindie.ru/games/game/elementalis
Судейских отзывов: 4 - DmitriySklyarov, Saley, PoliKhai, HelenAllienPoe
Отзывы участников: 8 - epigrodel, dwang, ArcasHH, KTD, BobrikDobrik, Jil, pafan, SemenLisenko
Отзывы пользователей: 3 - liff, jikantao, SoSiSkA

Обработка: https://myindie.ru/games/game/grimuar-dyavola
Судейских отзывов: 4 - PoliKhai, HelenAllienPoe, Saley, DmitriySklyarov
Отзывы участников: 6 - GhosDist, pafan, SemenLisenko, GamerGrapes, Heshi, buZZi6X
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/v-dome-s-gulem
Судейских отзывов: 1 - PoliKhai
Отзывы участников: 8 - sasha, JayxK, ArcasHH, GhosDist, KTD, SemenLisenko, pafan, Ivancorej
Отзывы пользователей: 1 - Rosie_Vi

Обработка: https://myindie.ru/games/game/unity-cult_b8i
Судейских отзывов: 4 - DmitriySklyarov, Saley, HelenAllienPoe, PoliKhai
Отзывы участников: 16 - JayxK, GhosDist, Skyline_rozan, pafan, Lacost, BobrikDobrik, Tafari, epigrodel, AndreyFish, Heshi, ArcasHH, buZZi6X, Zarya61, Pinecom, Dionis_369, KTD
Отзывы пользователей: 15 - Random_Aizer217, Pompom, Markus_Glevera, jikantao, keglia, Makswell376, UnrealQW, Redstarzo, geyker, Nestea, molodoy_venerez, mclovin, niconikita, Rramad, Taburetka

Обработка: https://myindie.ru/games/game/ne-proiznosi
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 4 - KTD, pafan, GamerGrapes, SemenLisenko
Отзывы пользователей: 2 - UnrealQW, dkotl

Обработка: https://myindie.ru/games/game/holy-fraud
Судейских отзывов: 0 -
Отзывы участников: 5 - phanopera, KTD, SemenLisenko, ArcasHH, pafan
Отзывы пользователей: 1 - Vlad_Borets

Обработка: https://myindie.ru/games/game/dead-channel
Судейских отзывов: 4 - DmitriySklyarov, PoliKhai, Saley, HelenAllienPoe
Отзывы участников: 13 - epigrodel, dwang, Skyline_rozan, pafan, Ivancorej, Zarya61, ArcasHH, YuraBulba, Jil, Lacost, SemenLisenko, kafel, Crp
Отзывы пользователей: 7 - matiabortysha, ille, eturnercus, glhf, ignis, dkotl, Taburetka

Обработка: https://myindie.ru/games/game/poluchi-lyubov
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 11 - JayxK, ArcasHH, phanopera, sasha, BobrikDobrik, KTD, pafan, peped, Ivancorej, SemenLisenko, CreatorLynx
Отзывы пользователей: 2 - UnrealQW, jikantao

Обработка: https://myindie.ru/games/game/the-mystery-of-the-cult-of-bokkult
Судейских отзывов: 0 -
Отзывы участников: 4 - KTD, pafan, SemenLisenko, WoltIx
Отзывы пользователей: 4 - UnrealQW, PurpleGames, ImmortalSheet, SerikVSerenkih

Обработка: https://myindie.ru/games/game/illuminati-confirmed
Судейских отзывов: 4 - DmitriySklyarov, PoliKhai, Saley, HelenAllienPoe
Отзывы участников: 10 - phanopera, ArcasHH, epigrodel, dwang, sasha, KTD, GamerGrapes, pafan, Lacost, SemenLisenko
Отзывы пользователей: 2 - AutoBobUs, Null

Обработка: https://myindie.ru/games/game/the-final-trial
Судейских отзывов: 0 -
Отзывы участников: 7 - KTD, SemenLisenko, pafan, Lacost, Ivancorej, Skyline_rozan, Deleted user 33d3f881
Отзывы пользователей: 2 - SoSiSkA, dodo

Обработка: https://myindie.ru/games/game/occultube
Судейских отзывов: 4 - PoliKhai, Saley, HelenAllienPoe, DmitriySklyarov
Отзывы участников: 10 - phanopera, dwang, KTD, SemenLisenko, ArcasHH, JayxK, pafan, Lacost, epigrodel, CreatorLynx
Отзывы пользователей: 5 - ignis, Chris_Kalin, UnrealQW, Rramad, Paulseagull

Обработка: https://myindie.ru/games/game/acooltism
Судейских отзывов: 0 -
Отзывы участников: 9 - sasha, KTD, GamerGrapes, pafan, SemenLisenko, buZZi6X, Pinecom, Dionis_369, kafel
Отзывы пользователей: 2 - Null, liff

Обработка: https://myindie.ru/games/game/desktop-demon
Судейских отзывов: 0 -
Отзывы участников: 9 - ArcasHH, Ivancorej, GamerGrapes, pafan, Lacost, Pinecom, epigrodel, SemenLisenko, Dionis_369
Отзывы пользователей: 2 - SerikVSerenkih, liff

Обработка: https://myindie.ru/games/game/cult-gatekeeper_btl
Судейских отзывов: 3 - Saley, DmitriySklyarov, PoliKhai
Отзывы участников: 11 - JayxK, phanopera, KTD, Skyline_rozan, pafan, GamerGrapes, SemenLisenko, Lacost, kafel, ArcasHH, buZZi6X
Отзывы пользователей: 1 - DanilRyzhkov

Обработка: https://myindie.ru/games/game/sigil
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 10 - JayxK, ArcasHH, dwang, pafan, GamerGrapes, Skyline_rozan, Lacost, SemenLisenko, Deleted user 33d3f881, bRokesy
Отзывы пользователей: 0 -

Обработка: https://myindie.ru/games/game/wake-the-fallen
Судейских отзывов: 0 -
Отзывы участников: 6 - phanopera, ArcasHH, pafan, Lacost, KTD, SemenLisenko
Отзывы пользователей: 4 - ignis, Gazan67, Useless_, LerekerUseless

Обработка: https://myindie.ru/games/game/my-ne-sekta-no-eto-ne-tochno
Судейских отзывов: 3 - PoliKhai, Saley, DmitriySklyarov
Отзывы участников: 11 - GhosDist, phanopera, Har_On, KTD, GamerGrapes, SemenLisenko, pafan, Skyline_rozan, kafel, buZZi6X, Pinecom
Отзывы пользователей: 3 - Markus_Glevera, mclovin, Rramad

Обработка: https://myindie.ru/games/game/chislo-zverya
Судейских отзывов: 4 - DmitriySklyarov, PoliKhai, Saley, HelenAllienPoe
Отзывы участников: 10 - epigrodel, sasha, dwang, ArcasHH, pafan, Lacost, SemenLisenko, Jil, buZZi6X, Deleted user 33d3f881
Отзывы пользователей: 1 - vcheslavk

Обработка: https://myindie.ru/games/game/ritual_xkq
Судейских отзывов: 0 -
Отзывы участников: 7 - JayxK, ArcasHH, sasha, SemenLisenko, Skyline_rozan, pafan, KTD
Отзывы пользователей: 2 - Taburetka, tenko

Обработка: https://myindie.ru/games/game/liniya-666
Судейских отзывов: 4 - PoliKhai, HelenAllienPoe, Saley, DmitriySklyarov
Отзывы участников: 12 - epigrodel, ArcasHH, dwang, GamerGrapes, Lacost, Ivancorej, SemenLisenko, KTD, pafan, Skyline_rozan, Deleted user 33d3f881, buZZi6X
Отзывы пользователей: 8 - vikpro07, GreatPasta, glhf, Karkov, SoSiSkA, Farshik52, dablyouu, Rramad

Обработка: https://myindie.ru/games/game/prizyv
Судейских отзывов: 0 -
Отзывы участников: 9 - KTD, GhosDist, peped, Ivancorej, pafan, Tafari, buZZi6X, Zarya61, SemenLisenko
Отзывы пользователей: 4 - liff, Markus_Glevera, UnrealQW, Farshik52

Обработка: https://myindie.ru/games/game/tajna-cerkvi
Судейских отзывов: 0 -
Отзывы участников: 4 - Har_On, pafan, SemenLisenko, KTD
Отзывы пользователей: 2 - UnrealQW, whaledevelop


Всего судейских отзывов на джеме: 120
Всего отзывов участников на джеме: 578
Всего отзывов пользователей на джеме: 186

In [40]:
# game_reviews

In [41]:
jam_games_file.close()

# 3. Обработка данных и анализ

In [54]:
# print(json.dumps(all_judges_reviews, ensure_ascii=False, indent=2))
# print(json.dumps(all_participant_reviews, ensure_ascii=False, indent=2))
# print(json.dumps(all_users_reviews, ensure_ascii=False, indent=2))

3.1 Обрабатываем все судейские отзывы и оценки для каждой игры

In [ ]:
# Словари для хранения данных судей
judges_dict = {} # userId -> {"username": username, "reviews": []}

for review in all_judges_reviews:
    if review.get('reviewerType') == 'judge':
        user_id = review.get('userId')
        username = review.get('user', {}).get('username', 'Unknown')

        if user_id not in judges_dict:
            judges_dict[user_id] = {
                "username": username,
                "reviews": []
            }

        judges_dict[user_id]["reviews"].append(review)

judges_dict = dict(sorted(judges_dict.items(), key=lambda item: len(item[1]['reviews']), reverse=True))

print(f"Количество уникальных судей: {len(judges_dict)}")
for user_id, info in judges_dict.items():
    print(f"Судья: {info['username']} (ID: {user_id}) - Обзоров: {len(info['reviews'])}")

# Финальный словарь с идентификацией по username
judges_reviews_by_username = {info['username']: info['reviews'] for info in judges_dict.values()}

Количество уникальных судей: 4
Судья: PoliKhai (ID: c739f699-9424-4039-9c0b-8b26a6f0f1c2) - Обзоров: 41
Судья: DmitriySklyarov (ID: 9b681ea6-e7cb-489e-bae7-0e07607f93d4) - Обзоров: 33
Судья: Saley (ID: 6ddb6287-691d-41f2-a7db-5df11f84c1cf) - Обзоров: 32
Судья: HelenAllienPoe (ID: db51c67e-9d3c-4e25-a589-ec045a0cdb62) - Обзоров: 14

In [44]:
# print(json.dumps(judges_reviews_by_username, ensure_ascii=False, indent=2))

3.1.1 Обрабатываем все отзывы участников джема и оценки для каждой игры

In [ ]:
# Словари для хранения данных участников джема
participants_dict = {} # userId -> {"username": username, "reviews": []}

for review in all_participant_reviews:
    if review.get('reviewerType') == 'jam-participant':
        user_id = review.get('userId')
        username = review.get('user', {}).get('username', 'Unknown')

        if user_id not in participants_dict:
            participants_dict[user_id] = {
                "username": username,
                "reviews": []
            }

        participants_dict[user_id]["reviews"].append(review)

participants_dict = dict(sorted(participants_dict.items(), key=lambda item: len(item[1]['reviews']), reverse=True))

print(f"Количество уникальных участников джема: {len(participants_dict)}")
for user_id, info in participants_dict.items():
    print(f"Участник джема: {info['username']} (ID: {user_id}) - Обзоров: {len(info['reviews'])}")

# Финальный словарь с идентификацией по username
participants_reviews_by_username = {info['username']: info['reviews'] for info in participants_dict.values()}

Количество уникальных участников джема: 43
Участник джема: pafan (ID: 89fb48cf-fad9-414e-ab0b-4f15a459ea54) - Обзоров: 66
Участник джема: SemenLisenko (ID: c0d4dd24-f39f-4942-84ba-be017ca1a0d3) - Обзоров: 66
Участник джема: KTD (ID: ee1c15e2-9f72-4aff-9849-1334ac6c4111) - Обзоров: 49
Участник джема: ArcasHH (ID: 57ecbb87-3217-4cc9-9f07-efbc378e92a2) - Обзоров: 32
Участник джема: Lacost (ID: beca03f4-f109-49ba-9451-24844c558782) - Обзоров: 24
Участник джема: Skyline_rozan (ID: eb0a4a15-8b6c-4d1b-9f23-27ff97343ee2) - Обзоров: 23
Участник джема: buZZi6X (ID: 8cb9624c-fe85-4fec-aeba-6be51d927fd9) - Обзоров: 23
Участник джема: JayxK (ID: 21cf988c-1d47-4615-8c5b-f81866ea19a9) - Обзоров: 23
Участник джема: GamerGrapes (ID: acee7cf0-0228-4ff1-bef1-2d12a03ad335) - Обзоров: 21
Участник джема: phanopera (ID: 66e8ace1-adf9-4d3d-8354-8ec0aab4076c) - Обзоров: 20
Участник джема: sasha (ID: c75bcb7b-9f3f-479a-a56a-2bb41296f5f4) - Обзоров: 19
Участник джема: GhosDist (ID: 1d0479d0-c97e-4a69-8e3f-caf34bc46821) - Обзоров: 18
Участник джема: Ivancorej (ID: 207a38c6-c3f7-4bd1-a97c-29933f248796) - Обзоров: 16
Участник джема: epigrodel (ID: 823028cb-774b-4352-ba45-2b906dedf7f9) - Обзоров: 16
Участник джема: Tafari (ID: cb3fb020-41d8-4005-ac69-63300c0a12cb) - Обзоров: 15
Участник джема: Zarya61 (ID: ffdb26e3-c2d6-4226-9b89-b596c3a526b1) - Обзоров: 14
Участник джема: Deleted user 33d3f881 (ID: 33d3f881-77cc-4cf8-aa0e-7de94141cd28) - Обзоров: 11
Участник джема: Pinecom (ID: a70ab381-d728-448b-ac04-bad29f4d2ab2) - Обзоров: 11
Участник джема: peped (ID: a62badb8-5f76-47d9-8c77-fef4b7ab877f) - Обзоров: 10
Участник джема: kafel (ID: da34628d-baa7-437e-8e87-c4a53c57f9b2) - Обзоров: 10
Участник джема: BobrikDobrik (ID: ff0e9dad-6aaa-43a8-814b-8b7aa2ee1601) - Обзоров: 10
Участник джема: Heshi (ID: f418e430-fd32-401f-aed4-3100ddb2b18c) - Обзоров: 10
Участник джема: dwang (ID: 1c9ae034-0dba-4579-9bdf-7467d0a6ca4b) - Обзоров: 10
Участник джема: Har_On (ID: e4535047-afd3-4eb8-aad7-8881df25455d) - Обзоров: 9
Участник джема: CreatorLynx (ID: 9144ec6d-7c00-4139-a5ca-798e7c4424b3) - Обзоров: 7
Участник джема: Jil (ID: 45570a65-df71-4484-895a-faea6c230df9) - Обзоров: 6
Участник джема: Dionis_369 (ID: 37be97cf-1b08-451a-8752-37c255fbdf28) - Обзоров: 6
Участник джема: WoltIx (ID: c2742ddb-1773-4a7c-9082-81001c5053d4) - Обзоров: 4
Участник джема: YuraBulba (ID: 819d11c2-3cca-4bb7-8316-f4f0d673b2aa) - Обзоров: 4
Участник джема: NaLLsuR (ID: f1683afa-2f35-4f89-80be-e5d3d5afc2d1) - Обзоров: 4
Участник джема: Crp (ID: 9459c71f-2ac3-4c0b-a620-a74ccc05bf00) - Обзоров: 3
Участник джема: Trase (ID: 03851d6a-303a-4ea1-91bc-ac1fba240627) - Обзоров: 3
Участник джема: yurimavt (ID: c6f9ea0b-430a-42f6-8728-5b6da82f8501) - Обзоров: 2
Участник джема: AlexeySergeevich (ID: f2934424-eeb3-446d-907f-3e9acc1dc187) - Обзоров: 2
Участник джема: Bogila (ID: 9bcfe351-84a7-420a-b9e1-37c7151cd45a) - Обзоров: 2
Участник джема: AndreyFish (ID: 27ecbd19-a2bf-48a1-b4c7-fbfc16240a97) - Обзоров: 2
Участник джема: chepuxxx (ID: 2302000a-23b2-4031-8407-26a787b3ac2c) - Обзоров: 1
Участник джема: bolshoj_bob (ID: 1f21727c-c844-4be0-bfb1-7405387fd240) - Обзоров: 1
Участник джема: HenjTV (ID: 47b90a73-446b-4850-ae0b-d5259ee1340b) - Обзоров: 1
Участник джема: Veles (ID: 56aee71a-d6b0-4ca7-8e0a-cee9e91d1546) - Обзоров: 1
Участник джема: Kosd (ID: 0df1f116-987f-48a8-bcf1-9386726c4716) - Обзоров: 1
Участник джема: JantayBerikbaev (ID: 55bc6097-4ca2-47a3-a032-a00563f80f49) - Обзоров: 1
Участник джема: bRokesy (ID: 95e3dbf2-3f23-4c28-913b-b56c82581bdc) - Обзоров: 1

In [46]:
# print(json.dumps(participants_reviews_by_username, ensure_ascii=False, indent=2))

3.2 Собираем статистику по каждому судье: средний балл, количество оценок, количество отзывов

In [68]:
judges_stats = []

for username, reviews in judges_reviews_by_username.items():
    if not reviews:
        print(f"* Судья {username} не имеет обзоров, пропускаем.")
        continue

    totals = { 'score': [] }
    for criteria in CRITERIAS:
        totals[criteria] = []

    for r in reviews:
        if 'score' in r:
            totals['score'].append(r['score'])

        c = r.get('criterias', {})
        for criteria in CRITERIAS:
            if criteria in c:
                totals[criteria].append(c[criteria])

    judge_row = {
        'username': username,
        'reviews_count': len(reviews)
    }

    for key, values in totals.items():
        judge_row[f'avg_{key}'] = round(sum(values) / len(values), 3) if values else 0

    judges_stats.append(judge_row)

df_judges_stats = pd.DataFrame(judges_stats)

# Вывод результата, отсортированного по среднему баллу
df_judges_stats.sort_values(by='avg_score', ascending=False)

,username,reviews_count,avg_score,avg_art,avg_sound,avg_theme,avg_gameplay,avg_narrative,avg_overall_impression
3,HelenAllienPoe,14,3.829,4.071,4.143,4.143,3.536,3.357,3.679
2,Saley,32,3.528,4.094,3.562,3.422,3.031,3.344,3.609
0,PoliKhai,41,3.305,3.451,3.207,3.695,2.829,3.305,3.268
1,DmitriySklyarov,33,3.115,3.788,3.212,2.833,2.788,2.970,3.015

3.2.1 Собираем статистику по каждому участнику джема: средний балл, количество оценок, количество отзывов

In [69]:
participants_stats = []

for username, reviews in participants_reviews_by_username.items():
    if not reviews:
        print(f"* Участник джема {username} не имеет обзоров, пропускаем.")
        continue

    totals = { 'score': [] }
    for criteria in CRITERIAS:
        totals[criteria] = []

    for r in reviews:
        if 'score' in r:
            totals['score'].append(r['score'])

        c = r.get('criterias', {})
        for criteria in CRITERIAS:
            if criteria in c:
                totals[criteria].append(c[criteria])

    participant_row = {
        'username': username,
        'reviews_count': len(reviews)
    }

    for key, values in totals.items():
        participant_row[f'avg_{key}'] = round(sum(values) / len(values), 3) if values else 0

    participants_stats.append(participant_row)

df_participants_stats = pd.DataFrame(participants_stats)

# Вывод результата, отсортированного по среднему баллу
df_participants_stats.sort_values(by='avg_score', ascending=False)

,username,reviews_count,avg_score,avg_art,avg_sound,avg_theme,avg_gameplay,avg_narrative,avg_overall_impression
36,chepuxxx,1,5.000,5.000,5.000,5.000,5.000,5.000,5.000
39,Veles,1,5.000,5.000,5.000,5.000,5.000,5.000,5.000
34,Bogila,2,4.500,5.000,5.000,5.000,3.250,5.000,3.750
20,BobrikDobrik,10,4.220,4.450,4.000,4.400,4.150,4.000,4.300
25,Jil,6,4.150,4.250,4.250,3.917,4.333,3.750,4.333
42,bRokesy,1,4.000,3.500,4.000,4.500,3.500,4.000,4.500
3,ArcasHH,32,3.928,4.094,4.188,4.156,3.406,4.250,3.453
33,AlexeySergeevich,2,3.900,4.000,4.000,4.750,3.250,3.750,3.500
16,Deleted user 33d3f881,11,3.836,3.545,3.409,4.545,3.455,3.727,4.273
26,Dionis_369,6,3.800,3.750,4.250,4.500,3.083,3.500,3.750
13,epigrodel,16,3.719,4.031,4.500,4.375,2.906,3.562,2.875
18,peped,10,3.680,4.050,3.400,4.050,3.350,3.650,3.500
12,Ivancorej,16,3.631,3.625,3.562,3.969,3.594,3.281,3.688
27,WoltIx,4,3.625,3.375,3.750,3.375,3.625,3.625,4.000
23,Har_On,9,3.589,4.222,3.833,3.389,2.722,3.444,3.833
7,JayxK,23,3.535,4.217,3.587,4.065,2.696,3.348,3.239
1,SemenLisenko,66,3.512,3.886,3.614,3.652,3.318,3.364,3.182
30,Crp,3,3.467,4.000,4.000,2.667,3.167,3.167,3.667
17,Pinecom,11,3.445,3.500,3.545,4.091,2.727,3.636,3.136
37,bolshoj_bob,1,3.300,5.000,3.000,3.500,3.500,3.000,2.000
6,buZZi6X,23,3.300,3.696,3.413,3.326,3.196,2.935,3.152
8,GamerGrapes,21,3.271,3.214,3.238,3.905,3.000,3.071,3.119
35,AndreyFish,2,3.250,3.750,3.250,2.750,3.000,3.000,3.750
9,phanopera,20,3.245,3.600,3.550,4.350,2.400,2.925,2.650
5,Skyline_rozan,23,3.217,3.761,2.848,3.652,2.891,2.891,3.239
21,Heshi,10,3.130,3.350,2.700,3.050,3.050,3.450,3.200
2,KTD,49,3.110,3.561,3.378,3.367,2.847,2.888,2.592
11,GhosDist,18,3.094,3.361,3.194,3.111,2.417,3.056,3.361
29,NaLLsuR,4,3.075,4.375,3.250,2.250,2.125,3.000,3.375
10,sasha,19,3.058,3.474,3.263,3.289,3.053,2.211,2.974
22,dwang,10,3.010,3.250,3.600,3.900,2.100,2.750,2.400
41,JantayBerikbaev,1,3.000,3.000,2.000,3.000,4.000,3.000,3.000
19,kafel,10,3.000,2.300,2.850,4.250,2.850,3.200,2.550
4,Lacost,24,2.971,3.354,2.750,3.875,2.396,2.729,2.708
32,yurimavt,2,2.950,3.000,3.500,4.000,2.000,2.750,2.250
28,YuraBulba,4,2.825,2.875,3.500,2.125,2.000,3.625,2.750
15,Zarya61,14,2.607,2.786,2.679,3.036,2.679,2.000,2.429
24,CreatorLynx,7,2.529,2.786,2.143,3.643,1.357,2.929,2.214
0,pafan,66,2.523,2.826,2.538,3.152,2.106,2.098,2.386
31,Trase,3,2.300,3.167,2.500,2.833,1.833,1.333,2.000
14,Tafari,15,2.220,2.367,2.300,1.967,2.133,2.100,2.467
40,Kosd,1,1.300,1.500,2.000,1.500,1.000,1.000,1.000
38,HenjTV,1,1.000,1.000,1.000,1.000,1.000,1.000,1.000

3.3 Cтатистический анализ: средние оценки, медианы, стандартные отклонения, распределения оценок и длины отзывов

In [70]:
judge_detailed_stats = []

for username, reviews in judges_reviews_by_username.items():
    judge_precise_scores = []
    judge_review_lengths = []

    for r in reviews:
        c = r.get('criterias', {})
        crit_values = [c[k] for k in CRITERIAS if k in c]

        if crit_values:
            game_score = sum(crit_values) / len(crit_values)
            judge_precise_scores.append(game_score)

        text = r.get('reviewText', '')
        if text:
            clean_text = re.sub(r'<[^>]+>', '', text)
            judge_review_lengths.append(len(clean_text))

    stats = {
        'username': username,
        'min_score': np.min(judge_precise_scores) if judge_precise_scores else 0.0,
        'max_score': np.max(judge_precise_scores) if judge_precise_scores else 0.0,
        'median_score': np.median(judge_precise_scores) if judge_precise_scores else 0.0,
        'std_score': np.std(judge_precise_scores) if judge_precise_scores else 0.0,
        'avg_review_chars': int(np.mean(judge_review_lengths)) if judge_review_lengths else 0.0,
        'min_review_chars': np.min(judge_review_lengths) if judge_review_lengths else 0,
        'max_review_chars': np.max(judge_review_lengths) if judge_review_lengths else 0
    }
    judge_detailed_stats.append(stats)

df_judge_detailed = pd.DataFrame(judge_detailed_stats)

df_judge_final_stats = pd.merge(df_judges_stats, df_judge_detailed, on='username')

cols = ['username', 'reviews_count', 'avg_score', 'median_score', 'std_score', 'min_score', 'max_score', 'avg_review_chars', 'min_review_chars', 'max_review_chars']
df_judge_final_stats[cols].sort_values(by='avg_score', ascending=False)

,username,reviews_count,avg_score,median_score,std_score,min_score,max_score,avg_review_chars,min_review_chars,max_review_chars
3,HelenAllienPoe,14,3.829,3.917,0.485,2.917,4.583,572,72,1038
2,Saley,32,3.528,3.500,0.671,2.083,4.667,777,411,2139
0,PoliKhai,41,3.305,3.417,0.783,1.083,4.667,532,69,1350
1,DmitriySklyarov,33,3.115,3.083,0.666,1.500,4.250,591,292,1458

3.3.1 Cтатистический анализ: средние оценки, медианы, стандартные отклонения, распределения оценок и длины отзывов

In [71]:
participants_detailed_stats = []

for username, reviews in participants_reviews_by_username.items():
    participant_precise_scores = []
    participant_review_lengths = []

    for r in reviews:
        c = r.get('criterias', {})
        crit_values = [c[k] for k in CRITERIAS if k in c]

        if crit_values:
            game_score = sum(crit_values) / len(crit_values)
            participant_precise_scores.append(game_score)

        text = r.get('reviewText', '')
        if text:
            clean_text = re.sub(r'<[^>]+>', '', text)
            participant_review_lengths.append(len(clean_text))

    stats = {
        'username': username,
        'min_score': np.min(participant_precise_scores) if participant_precise_scores else 0.0,
        'max_score': np.max(participant_precise_scores) if participant_precise_scores else 0.0,
        'median_score': np.median(participant_precise_scores) if participant_precise_scores else 0.0,
        'std_score': np.std(participant_precise_scores) if participant_precise_scores else 0.0,
        'avg_review_chars': int(np.mean(participant_review_lengths)) if participant_review_lengths else 0.0,
        'min_review_chars': np.min(participant_review_lengths) if participant_review_lengths else 0,
        'max_review_chars': np.max(participant_review_lengths) if participant_review_lengths else 0
    }
    participants_detailed_stats.append(stats)

df_participants_detailed = pd.DataFrame(participants_detailed_stats)

df_participants_final_stats = pd.merge(df_participants_stats, df_participants_detailed, on='username')

cols = ['username', 'reviews_count', 'avg_score', 'median_score', 'std_score', 'min_score', 'max_score', 'avg_review_chars', 'min_review_chars', 'max_review_chars']
df_participants_final_stats[cols].sort_values(by='avg_score', ascending=False)

,username,reviews_count,avg_score,median_score,std_score,min_score,max_score,avg_review_chars,min_review_chars,max_review_chars
36,chepuxxx,1,5.000,5.000,0.000,5.000,5.000,344.000,344,344
39,Veles,1,5.000,5.000,0.000,5.000,5.000,147.000,147,147
34,Bogila,2,4.500,4.500,0.500,4.000,5.000,212.000,152,272
20,BobrikDobrik,10,4.220,4.542,0.684,2.667,4.917,551.000,197,948
25,Jil,6,4.150,4.167,0.404,3.333,4.583,458.000,190,672
42,bRokesy,1,4.000,4.000,0.000,4.000,4.000,330.000,330,330
3,ArcasHH,32,3.928,4.000,0.536,2.583,4.667,615.000,114,1184
33,AlexeySergeevich,2,3.900,3.875,0.625,3.250,4.500,133.000,73,193
16,Deleted user 33d3f881,11,3.836,4.167,0.809,1.833,4.667,0.000,0,0
26,Dionis_369,6,3.800,3.750,0.627,3.000,5.000,240.000,0,478
13,epigrodel,16,3.719,3.917,1.012,1.000,4.917,368.000,44,739
18,peped,10,3.680,3.833,0.606,2.583,4.500,7.000,0,25
12,Ivancorej,16,3.631,3.875,1.066,1.667,5.000,288.000,126,536
27,WoltIx,4,3.625,3.750,0.940,2.417,4.583,66.000,25,121
23,Har_On,9,3.589,3.750,0.894,1.500,4.750,69.000,69,69
7,JayxK,23,3.535,3.500,0.574,2.333,4.583,49.000,0,138
1,SemenLisenko,66,3.512,3.542,0.988,1.083,5.000,520.000,20,2498
30,Crp,3,3.467,3.167,0.515,3.000,4.167,60.000,18,106
17,Pinecom,11,3.445,3.667,0.711,1.583,4.083,296.000,46,680
37,bolshoj_bob,1,3.300,3.333,0.000,3.333,3.333,407.000,407,407
6,buZZi6X,23,3.300,3.667,1.064,1.333,4.917,158.000,0,650
8,GamerGrapes,21,3.271,3.250,0.863,1.500,4.500,248.000,0,594
35,AndreyFish,2,3.250,3.250,0.167,3.083,3.417,214.000,134,295
9,phanopera,20,3.245,3.167,0.687,1.917,4.667,93.000,0,322
5,Skyline_rozan,23,3.217,3.500,0.967,1.167,4.417,330.000,76,718
21,Heshi,10,3.130,3.083,1.341,1.333,5.000,127.000,0,389
2,KTD,49,3.110,3.167,1.237,1.000,5.000,52.000,0,137
11,GhosDist,18,3.094,3.083,0.729,1.417,4.500,409.000,63,1280
29,NaLLsuR,4,3.075,3.083,0.160,2.833,3.250,245.000,128,573
10,sasha,19,3.058,3.167,0.853,1.250,4.167,318.000,0,761
22,dwang,10,3.010,2.958,0.544,2.000,3.917,452.000,192,646
41,JantayBerikbaev,1,3.000,3.000,0.000,3.000,3.000,0.000,0,0
19,kafel,10,3.000,2.875,1.044,1.167,4.333,182.000,0,343
4,Lacost,24,2.971,2.958,0.760,1.167,4.583,149.000,0,417
32,yurimavt,2,2.950,2.917,0.750,2.167,3.667,0.000,0,0
28,YuraBulba,4,2.825,2.833,1.116,1.250,4.333,0.000,0,0
15,Zarya61,14,2.607,2.833,0.967,1.083,3.917,92.000,0,199
24,CreatorLynx,7,2.529,2.750,0.795,1.417,3.750,892.000,355,1866
0,pafan,66,2.523,2.417,0.659,1.333,4.250,172.000,0,941
31,Trase,3,2.300,2.750,0.728,1.250,2.833,68.000,16,120
14,Tafari,15,2.220,1.917,0.765,1.417,4.167,0.000,0,0
40,Kosd,1,1.300,1.333,0.000,1.333,1.333,251.000,251,251
38,HenjTV,1,1.000,1.000,0.000,1.000,1.000,697.000,697,697

3.4 Больше статистики судей:
* strictness_index (индекс "строгости"): Отрицательный = строгий, Положительный = добрый

Строгость считается от среднего значения оценок, выставленных судьями. Если судья ставит в среднем низкие оценки, то он считается строгим, если высокие -- добрым. Этот индекс может быть полезен для анализа "везучести" игр.

In [72]:
judges_deep_insights = []

all_judges_precise_scores = []
for reviews in judges_reviews_by_username.values():
    for r in reviews:
        c = r.get('criterias', {})
        crit_values = [c[k] for k in CRITERIAS if k in c]
        if crit_values:
            all_judges_precise_scores.append(sum(crit_values) / len(crit_values))

judges_global_avg = np.mean(all_judges_precise_scores) if all_judges_precise_scores else 0.0

for username, reviews in judges_reviews_by_username.items():
    if not reviews: continue

    judge_precise_scores = []
    judge_review_dates = []

    # Статистика по критериям для этого судьи
    criteria_totals = {k: [] for k in CRITERIAS}

    for r in reviews:
        c = r.get('criterias', {})
        cv = [c[k] for k in CRITERIAS if k in c]
        if cv:
            judge_precise_scores.append(sum(cv)/len(cv))

        for k in CRITERIAS:
            if k in c: criteria_totals[k].append(c[k])

        # Время
        dt_str = r.get('createdAt')
        if dt_str:
            dt = datetime.strptime(dt_str, "%Y-%m-%dT%H:%M:%S.%fZ")
            judge_review_dates.append(dt.date())

    # любимый и нелюбимый критерий (avg)
    crit_avgs = {k: np.mean(v) if v else 0 for k, v in criteria_totals.items()}
    best_crit = max(crit_avgs, key=crit_avgs.get)
    worst_crit = min(crit_avgs, key=crit_avgs.get)

    judge_avg = np.mean(judge_precise_scores) if judge_precise_scores else 0.0

    insight = {
        'username': username,
        'strictness_index': round(judge_avg - judges_global_avg, 3), # Отрицательный = строгий, Положительный = добрый
        'top_criteria': f"{best_crit} ({round(crit_avgs[best_crit], 2)})",
        'bottom_criteria': f"{worst_crit} ({round(crit_avgs[worst_crit], 2)})",
        'active_days': (max(judge_review_dates) - min(judge_review_dates)).days + 1 if judge_review_dates else 0,
        'reviews_per_day': round(len(reviews) / ((max(judge_review_dates) - min(judge_review_dates)).days + 1), 2) if judge_review_dates else 0
    }
    judges_deep_insights.append(insight)

df_judges_insights = pd.DataFrame(judges_deep_insights)

df_judges_insights.sort_values(by='strictness_index')

,username,strictness_index,top_criteria,bottom_criteria,active_days,reviews_per_day
1,DmitriySklyarov,-0.259,art (3.79),gameplay (2.79),7,4.710
0,PoliKhai,-0.067,theme (3.7),gameplay (2.83),3,13.670
2,Saley,0.151,art (4.09),gameplay (3.03),3,10.670
3,HelenAllienPoe,0.462,sound (4.14),narrative (3.36),4,3.500

3.4.1 Больше статистики участников джема:
- strictness_index: Отрицательный = строгий, Положительный = добрый

In [74]:
participants_deep_insights = []

all_participants_precise_scores = []
for reviews in participants_reviews_by_username.values():
    for r in reviews:
        c = r.get('criterias', {})
        crit_values = [c[k] for k in CRITERIAS if k in c]
        if crit_values:
            all_participants_precise_scores.append(sum(crit_values) / len(crit_values))

participants_global_avg = np.mean(all_participants_precise_scores) if all_participants_precise_scores else 0.0

for username, reviews in participants_reviews_by_username.items():
    if not reviews: continue

    participant_precise_scores = []
    participant_review_dates = []

    # Статистика по критериям для этого участника
    criteria_totals = {k: [] for k in CRITERIAS}

    for r in reviews:
        c = r.get('criterias', {})
        cv = [c[k] for k in CRITERIAS if k in c]
        if cv:
            participant_precise_scores.append(sum(cv)/len(cv))

        for k in CRITERIAS:
            if k in c: criteria_totals[k].append(c[k])

        # Время
        dt_str = r.get('createdAt')
        if dt_str:
            dt = datetime.strptime(dt_str, "%Y-%m-%dT%H:%M:%S.%fZ")
            participant_review_dates.append(dt.date())

    # любимый и нелюбимый критерий (avg)
    crit_avgs = {k: np.mean(v) if v else 0 for k, v in criteria_totals.items()}
    best_crit = max(crit_avgs, key=crit_avgs.get)
    worst_crit = min(crit_avgs, key=crit_avgs.get)

    participant_avg = np.mean(participant_precise_scores) if participant_precise_scores else 0.0

    insight = {
        'username': username,
        'strictness_index': round(participant_avg - participants_global_avg, 3), # Отрицательный = строгий, Положительный = добрый
        'top_criteria': f"{best_crit} ({round(crit_avgs[best_crit], 2)})",
        'bottom_criteria': f"{worst_crit} ({round(crit_avgs[worst_crit], 2)})",
        'active_days': (max(participant_review_dates) - min(participant_review_dates)).days + 1 if participant_review_dates else 0,
        'reviews_per_day': round(len(reviews) / ((max(participant_review_dates) - min(participant_review_dates)).days + 1), 2) if participant_review_dates else 0
    }
    participants_deep_insights.append(insight)

df_participants_insights = pd.DataFrame(participants_deep_insights)

df_participants_insights.sort_values(by='strictness_index')

,username,strictness_index,top_criteria,bottom_criteria,active_days,reviews_per_day
38,HenjTV,-2.227,art (1.0),art (1.0),1,1.000
40,Kosd,-1.893,sound (2.0),gameplay (1.0),1,1.000
14,Tafari,-1.004,overall_impression (2.47),theme (1.97),1,15.000
31,Trase,-0.949,art (3.17),narrative (1.33),1,3.000
24,CreatorLynx,-0.715,theme (3.64),gameplay (1.36),3,2.330
0,pafan,-0.709,theme (3.15),narrative (2.1),3,22.000
15,Zarya61,-0.625,theme (3.04),narrative (2.0),2,7.000
28,YuraBulba,-0.414,narrative (3.62),gameplay (2.0),4,1.000
32,yurimavt,-0.310,theme (4.0),gameplay (2.0),1,2.000
4,Lacost,-0.258,theme (3.88),gameplay (2.4),4,6.000
22,dwang,-0.227,theme (3.9),gameplay (2.1),1,10.000
19,kafel,-0.227,theme (4.25),art (2.3),2,5.000
41,JantayBerikbaev,-0.227,gameplay (4.0),sound (2.0),1,1.000
10,sasha,-0.183,art (3.47),narrative (2.21),2,9.500
29,NaLLsuR,-0.164,art (4.38),gameplay (2.12),1,4.000
11,GhosDist,-0.143,art (3.36),gameplay (2.42),3,6.000
2,KTD,-0.121,art (3.56),overall_impression (2.59),5,9.800
21,Heshi,-0.093,narrative (3.45),sound (2.7),2,5.000
5,Skyline_rozan,-0.013,art (3.76),sound (2.85),4,5.750
9,phanopera,0.019,theme (4.35),gameplay (2.4),1,20.000
35,AndreyFish,0.023,art (3.75),theme (2.75),1,2.000
8,GamerGrapes,0.031,theme (3.9),gameplay (3.0),3,7.000
6,buZZi6X,0.060,art (3.7),narrative (2.93),1,23.000
37,bolshoj_bob,0.107,art (5.0),overall_impression (2.0),1,1.000
17,Pinecom,0.213,theme (4.09),gameplay (2.73),2,5.500
30,Crp,0.218,art (4.0),theme (2.67),2,1.500
1,SemenLisenko,0.276,art (3.89),overall_impression (3.18),3,22.000
7,JayxK,0.299,art (4.22),gameplay (2.7),3,7.670
23,Har_On,0.347,art (4.22),gameplay (2.72),1,9.000
12,Ivancorej,0.393,theme (3.97),narrative (3.28),1,16.000
27,WoltIx,0.398,overall_impression (4.0),art (3.38),2,2.000
18,peped,0.440,art (4.05),gameplay (3.35),1,10.000
13,epigrodel,0.482,sound (4.5),overall_impression (2.88),4,4.000
26,Dionis_369,0.579,theme (4.5),gameplay (3.08),1,6.000
16,Deleted user 33d3f881,0.599,theme (4.55),sound (3.41),1,11.000
33,AlexeySergeevich,0.648,theme (4.75),gameplay (3.25),1,2.000
3,ArcasHH,0.698,narrative (4.25),gameplay (3.41),4,8.000
42,bRokesy,0.773,theme (4.5),art (3.5),1,1.000
25,Jil,0.912,gameplay (4.33),narrative (3.75),3,2.000
20,BobrikDobrik,0.990,art (4.45),sound (4.0),3,3.330
34,Bogila,1.273,art (5.0),gameplay (3.25),1,2.000
36,chepuxxx,1.773,art (5.0),art (5.0),1,1.000
39,Veles,1.773,art (5.0),art (5.0),1,1.000

3.5 "Везучие" и "невезучие" игры

In [75]:
# Словари для быстрого поиска строгости
judge_strictness = df_judges_insights.set_index('username')['strictness_index'].to_dict()
participant_strictness = df_participants_insights.set_index('username')['strictness_index'].to_dict()

for alias, reviews in game_reviews.items():
    judges = reviews.get('judges', [])
    participants = reviews.get('participants', [])

    # Сбор данных по судьям
    j_info = []
    j_total_strictness = 0
    for r in judges:
        name = r.get('user', {}).get('username')
        strictness = judge_strictness.get(name, 0)
        j_info.append(f" {name} ({strictness})")
        j_total_strictness += strictness

    # Сбор данных по участникам
    p_info = []
    p_total_strictness = 0
    for r in participants:
        name = r.get('user', {}).get('username')
        strictness = participant_strictness.get(name, 0)
        p_info.append(f" {name} ({strictness})")
        p_total_strictness += strictness

    print(f"Игра: {alias}, URL: https://myindie.ru/games/game/{alias}")
    print(f"Судьи (строгость): {', '.join(j_info)}")
    print(f"Участники (строгость): {', '.join(p_info)}")
    print(f"Суммарная строгость судей: {round(j_total_strictness, 3)}")
    print(f"Суммарная строгость участников: {round(p_total_strictness, 3)}\n")

Игра: ultimatum-odna-noch-s-karachunom, URL: https://myindie.ru/games/game/ultimatum-odna-noch-s-karachunom
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  pafan (-0.709),  SemenLisenko (0.276),  GhosDist (-0.143),  Ivancorej (0.393),  KTD (-0.121),  chepuxxx (1.773),  ArcasHH (0.698),  Skyline_rozan (-0.013),  Tafari (-1.004),  Crp (0.218),  CreatorLynx (-0.715)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 0.653

Игра: trash-under-ground, URL: https://myindie.ru/games/game/trash-under-ground
Судьи (строгость):
Участники (строгость):  GhosDist (-0.143),  KTD (-0.121),  ArcasHH (0.698),  pafan (-0.709),  SemenLisenko (0.276),  Tafari (-1.004),  GamerGrapes (0.031),  Skyline_rozan (-0.013),  buZZi6X (0.06)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.925

Игра: cult-indie, URL: https://myindie.ru/games/game/cult-indie
Судьи (строгость):  DmitriySklyarov (-0.259),  Saley (0.151),  HelenAllienPoe (0.462),  PoliKhai (-0.067)
Участники (строгость):  JayxK (0.299),  phanopera (0.019),  GhosDist (-0.143),  pafan (-0.709),  Skyline_rozan (-0.013),  Jil (0.912),  SemenLisenko (0.276),  peped (0.44),  Tafari (-1.004),  kafel (-0.227),  epigrodel (0.482),  BobrikDobrik (0.99),  Zarya61 (-0.625),  KTD (-0.121),  Lacost (-0.258)
Суммарная строгость судей: 0.287
Суммарная строгость участников: 0.318

Игра: udivitelnyj-ded, URL: https://myindie.ru/games/game/udivitelnyj-ded
Судьи (строгость):  DmitriySklyarov (-0.259)
Участники (строгость):  GhosDist (-0.143),  pafan (-0.709),  WoltIx (0.398),  Ivancorej (0.393),  ArcasHH (0.698),  Skyline_rozan (-0.013),  Crp (0.218),  BobrikDobrik (0.99),  Lacost (-0.258),  buZZi6X (0.06),  Dionis_369 (0.579),  SemenLisenko (0.276)
Суммарная строгость судей: -0.259
Суммарная строгость участников: 2.489

Игра: franshiza-ktulhu_nx3, URL: https://myindie.ru/games/game/franshiza-ktulhu_nx3
Судьи (строгость):  HelenAllienPoe (0.462),  PoliKhai (-0.067)
Участники (строгость):  phanopera (0.019),  KTD (-0.121),  pafan (-0.709),  GamerGrapes (0.031),  SemenLisenko (0.276),  Deleted user 33d3f881 (0.599),  buZZi6X (0.06)
Суммарная строгость судей: 0.395
Суммарная строгость участников: 0.155

Игра: exorcismo, URL: https://myindie.ru/games/game/exorcismo
Судьи (строгость):
Участники (строгость):  phanopera (0.019),  pafan (-0.709),  JayxK (0.299),  Skyline_rozan (-0.013),  SemenLisenko (0.276),  Tafari (-1.004),  Lacost (-0.258),  Deleted user 33d3f881 (0.599),  Zarya61 (-0.625)
Суммарная строгость судей: 0
Суммарная строгость участников: -1.416

Игра: 5-days-with-the-necronomicon_opw, URL: https://myindie.ru/games/game/5-days-with-the-necronomicon_opw
Судьи (строгость):  Saley (0.151),  DmitriySklyarov (-0.259),  PoliKhai (-0.067)
Участники (строгость):  phanopera (0.019),  Skyline_rozan (-0.013),  KTD (-0.121),  SemenLisenko (0.276),  pafan (-0.709),  JayxK (0.299),  Heshi (-0.093)
Суммарная строгость судей: -0.175
Суммарная строгость участников: -0.342

Игра: full-moon-twin-rite, URL: https://myindie.ru/games/game/full-moon-twin-rite
Судьи (строгость):
Участники (строгость):  KTD (-0.121),  pafan (-0.709),  SemenLisenko (0.276),  Tafari (-1.004),  Deleted user 33d3f881 (0.599)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.959

Игра: zayachij-kult, URL: https://myindie.ru/games/game/zayachij-kult
Судьи (строгость):  PoliKhai (-0.067),  DmitriySklyarov (-0.259),  Saley (0.151)
Участники (строгость):  phanopera (0.019),  epigrodel (0.482),  ArcasHH (0.698),  pafan (-0.709),  JayxK (0.299),  GamerGrapes (0.031),  Lacost (-0.258),  SemenLisenko (0.276),  peped (0.44),  Ivancorej (0.393),  Zarya61 (-0.625),  kafel (-0.227),  buZZi6X (0.06),  KTD (-0.121)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 0.758

Игра: no-edward, URL: https://myindie.ru/games/game/no-edward
Судьи (строгость):  DmitriySklyarov (-0.259),  HelenAllienPoe (0.462),  PoliKhai (-0.067),  Saley (0.151)
Участники (строгость):  phanopera (0.019),  epigrodel (0.482),  dwang (-0.227),  KTD (-0.121),  Skyline_rozan (-0.013),  pafan (-0.709),  Lacost (-0.258),  Pinecom (0.213),  peped (0.44),  SemenLisenko (0.276)
Суммарная строгость судей: 0.287
Суммарная строгость участников: 0.102

Игра: protokol-pentagrammy, URL: https://myindie.ru/games/game/protokol-pentagrammy
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  sasha (-0.183),  pafan (-0.709),  Heshi (-0.093),  SemenLisenko (0.276),  Trase (-0.949),  KTD (-0.121)
Суммарная строгость судей: -0.067
Суммарная строгость участников: -1.779

Игра: all-hail-sister, URL: https://myindie.ru/games/game/all-hail-sister
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  GhosDist (-0.143),  sasha (-0.183),  SemenLisenko (0.276),  pafan (-0.709),  WoltIx (0.398),  Heshi (-0.093),  Pinecom (0.213),  yurimavt (-0.31),  Zarya61 (-0.625)
Суммарная строгость судей: -0.067
Суммарная строгость участников: -1.176

Игра: s-run_5pm, URL: https://myindie.ru/games/game/s-run_5pm
Судьи (строгость):
Участники (строгость):  phanopera (0.019),  KTD (-0.121),  pafan (-0.709),  SemenLisenko (0.276),  CreatorLynx (-0.715),  ArcasHH (0.698),  GamerGrapes (0.031),  Tafari (-1.004),  bolshoj_bob (0.107)
Суммарная строгость судей: 0
Суммарная строгость участников: -1.418

Игра: les, URL: https://myindie.ru/games/game/les
Судьи (строгость):  Saley (0.151),  DmitriySklyarov (-0.259),  PoliKhai (-0.067)
Участники (строгость):  JayxK (0.299),  phanopera (0.019),  Har_On (0.347),  pafan (-0.709),  SemenLisenko (0.276),  Pinecom (0.213),  Lacost (-0.258),  ArcasHH (0.698),  yurimavt (-0.31),  Deleted user 33d3f881 (0.599)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 1.174

Игра: curse-of-the-grail, URL: https://myindie.ru/games/game/curse-of-the-grail
Судьи (строгость):
Участники (строгость):  JayxK (0.299),  KTD (-0.121),  GamerGrapes (0.031),  pafan (-0.709),  SemenLisenko (0.276),  epigrodel (0.482),  HenjTV (-2.227),  Pinecom (0.213)
Суммарная строгость судей: 0
Суммарная строгость участников: -1.756

Игра: kul-pustoshi, URL: https://myindie.ru/games/game/kul-pustoshi
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  YuraBulba (-0.414),  sasha (-0.183),  Veles (1.773),  Kosd (-1.893),  Har_On (0.347),  SemenLisenko (0.276),  Ivancorej (0.393),  AlexeySergeevich (0.648),  BobrikDobrik (0.99),  buZZi6X (0.06)
Суммарная строгость судей: -0.067
Суммарная строгость участников: 1.997

Игра: bureau-of-accult-affairs_aaq, URL: https://myindie.ru/games/game/bureau-of-accult-affairs_aaq
Судьи (строгость):
Участники (строгость):  JayxK (0.299),  Skyline_rozan (-0.013),  ArcasHH (0.698),  KTD (-0.121),  pafan (-0.709),  SemenLisenko (0.276),  buZZi6X (0.06)
Суммарная строгость судей: 0
Суммарная строгость участников: 0.49

Игра: cultfire, URL: https://myindie.ru/games/game/cultfire
Судьи (строгость):
Участники (строгость):  sasha (-0.183),  KTD (-0.121),  pafan (-0.709),  Ivancorej (0.393),  SemenLisenko (0.276),  Tafari (-1.004),  buZZi6X (0.06),  Deleted user 33d3f881 (0.599)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.689

Игра: occulte, URL: https://myindie.ru/games/game/occulte
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  phanopera (0.019),  KTD (-0.121),  pafan (-0.709),  Lacost (-0.258),  Jil (0.912),  SemenLisenko (0.276),  Zarya61 (-0.625)
Суммарная строгость судей: -0.067
Суммарная строгость участников: -0.506

Игра: eyesless, URL: https://myindie.ru/games/game/eyesless
Судьи (строгость):
Участники (строгость):  sasha (-0.183),  KTD (-0.121),  SemenLisenko (0.276),  pafan (-0.709),  Ivancorej (0.393),  GamerGrapes (0.031),  Heshi (-0.093),  Lacost (-0.258),  CreatorLynx (-0.715)
Суммарная строгость судей: 0
Суммарная строгость участников: -1.379

Игра: mrachnyj-obet, URL: https://myindie.ru/games/game/mrachnyj-obet
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  KTD (-0.121),  pafan (-0.709),  SemenLisenko (0.276),  Tafari (-1.004),  kafel (-0.227)
Суммарная строгость судей: -0.067
Суммарная строгость участников: -1.785

Игра: oculus-ritual, URL: https://myindie.ru/games/game/oculus-ritual
Судьи (строгость):
Участники (строгость):  sasha (-0.183),  GhosDist (-0.143),  BobrikDobrik (0.99),  Skyline_rozan (-0.013),  SemenLisenko (0.276),  GamerGrapes (0.031),  pafan (-0.709),  Tafari (-1.004)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.755

Игра: deal-with-the-demon, URL: https://myindie.ru/games/game/deal-with-the-demon
Судьи (строгость):  DmitriySklyarov (-0.259),  PoliKhai (-0.067),  Saley (0.151)
Участники (строгость):  ArcasHH (0.698),  JayxK (0.299),  KTD (-0.121),  SemenLisenko (0.276),  pafan (-0.709),  buZZi6X (0.06)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 0.503

Игра: rybolovnyj-kult, URL: https://myindie.ru/games/game/rybolovnyj-kult
Судьи (строгость):  PoliKhai (-0.067),  HelenAllienPoe (0.462),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  JayxK (0.299),  sasha (-0.183),  Har_On (0.347),  ArcasHH (0.698),  pafan (-0.709),  Skyline_rozan (-0.013),  WoltIx (0.398),  peped (0.44),  SemenLisenko (0.276),  kafel (-0.227),  Heshi (-0.093),  Zarya61 (-0.625),  Bogila (1.273),  KTD (-0.121)
Суммарная строгость судей: 0.287
Суммарная строгость участников: 1.76

Игра: cult-of-the-deep-dungeon, URL: https://myindie.ru/games/game/cult-of-the-deep-dungeon
Судьи (строгость):
Участники (строгость):  GhosDist (-0.143),  ArcasHH (0.698),  SemenLisenko (0.276),  pafan (-0.709),  Heshi (-0.093),  CreatorLynx (-0.715)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.686

Игра: trust-us_7ak, URL: https://myindie.ru/games/game/trust-us_7ak
Судьи (строгость):  DmitriySklyarov (-0.259),  Saley (0.151),  PoliKhai (-0.067),  HelenAllienPoe (0.462)
Участники (строгость):  JayxK (0.299),  phanopera (0.019),  Har_On (0.347),  KTD (-0.121),  dwang (-0.227),  epigrodel (0.482),  sasha (-0.183),  ArcasHH (0.698),  pafan (-0.709),  Skyline_rozan (-0.013),  SemenLisenko (0.276),  peped (0.44),  Lacost (-0.258),  Ivancorej (0.393),  Zarya61 (-0.625),  AndreyFish (0.023),  kafel (-0.227),  buZZi6X (0.06)
Суммарная строгость судей: 0.287
Суммарная строгость участников: 0.674

Игра: chernobot, URL: https://myindie.ru/games/game/chernobot
Судьи (строгость):  PoliKhai (-0.067),  HelenAllienPoe (0.462),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  sasha (-0.183),  pafan (-0.709),  Lacost (-0.258),  SemenLisenko (0.276),  Deleted user 33d3f881 (0.599),  KTD (-0.121)
Суммарная строгость судей: 0.287
Суммарная строгость участников: -0.396

Игра: grimoire-of-the-void_flm, URL: https://myindie.ru/games/game/grimoire-of-the-void_flm
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  KTD (-0.121),  Lacost (-0.258),  ArcasHH (0.698),  pafan (-0.709),  Jil (0.912),  SemenLisenko (0.276)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 0.798

Игра: the-philosophers-stone, URL: https://myindie.ru/games/game/the-philosophers-stone
Судьи (строгость):
Участники (строгость):  YuraBulba (-0.414),  JayxK (0.299),  KTD (-0.121),  SemenLisenko (0.276),  GhosDist (-0.143),  pafan (-0.709),  Deleted user 33d3f881 (0.599)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.213

Игра: die-my-darling_nzc, URL: https://myindie.ru/games/game/die-my-darling_nzc
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  JayxK (0.299),  Har_On (0.347),  pafan (-0.709),  Trase (-0.949),  NaLLsuR (-0.164),  peped (0.44),  Zarya61 (-0.625),  buZZi6X (0.06),  Lacost (-0.258),  SemenLisenko (0.276)
Суммарная строгость судей: -0.175
Суммарная строгость участников: -1.283

Игра: pikovaya-dama-ritual-izgnaniya, URL: https://myindie.ru/games/game/pikovaya-dama-ritual-izgnaniya
Судьи (строгость):  DmitriySklyarov (-0.259),  PoliKhai (-0.067),  Saley (0.151)
Участники (строгость):  phanopera (0.019),  JayxK (0.299),  BobrikDobrik (0.99),  pafan (-0.709),  SemenLisenko (0.276),  KTD (-0.121),  GamerGrapes (0.031),  kafel (-0.227),  Zarya61 (-0.625)
Суммарная строгость судей: -0.175
Суммарная строгость участников: -0.067

Игра: crossswitch, URL: https://myindie.ru/games/game/crossswitch
Судьи (строгость):
Участники (строгость):  sasha (-0.183),  GhosDist (-0.143),  KTD (-0.121),  pafan (-0.709),  Tafari (-1.004),  SemenLisenko (0.276),  Pinecom (0.213)
Суммарная строгость судей: 0
Суммарная строгость участников: -1.671

Игра: tajna-alistera, URL: https://myindie.ru/games/game/tajna-alistera
Судьи (строгость):
Участники (строгость):  KTD (-0.121),  pafan (-0.709),  NaLLsuR (-0.164),  Lacost (-0.258),  GamerGrapes (0.031),  Tafari (-1.004),  SemenLisenko (0.276)
Суммарная строгость судей: 0
Суммарная строгость участников: -1.949

Игра: seer-for-hire_q3c, URL: https://myindie.ru/games/game/seer-for-hire_q3c
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  GhosDist (-0.143),  ArcasHH (0.698),  KTD (-0.121),  SemenLisenko (0.276),  pafan (-0.709),  peped (0.44),  buZZi6X (0.06)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 0.501

Игра: neofit, URL: https://myindie.ru/games/game/neofit
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  JayxK (0.299),  ArcasHH (0.698),  KTD (-0.121),  pafan (-0.709),  Trase (-0.949),  epigrodel (0.482),  AlexeySergeevich (0.648),  Skyline_rozan (-0.013),  SemenLisenko (0.276),  Bogila (1.273)
Суммарная строгость судей: -0.067
Суммарная строгость участников: 1.884

Игра: the-second-chance-agency, URL: https://myindie.ru/games/game/the-second-chance-agency
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  SemenLisenko (0.276),  pafan (-0.709),  KTD (-0.121)
Суммарная строгость судей: -0.175
Суммарная строгость участников: -0.554

Игра: godeath, URL: https://myindie.ru/games/game/godeath
Судьи (строгость):
Участники (строгость):  JayxK (0.299),  Har_On (0.347),  KTD (-0.121),  pafan (-0.709),  Skyline_rozan (-0.013),  GamerGrapes (0.031),  YuraBulba (-0.414),  Pinecom (0.213),  SemenLisenko (0.276)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.091

Игра: ravings, URL: https://myindie.ru/games/game/ravings
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  GhosDist (-0.143),  KTD (-0.121),  pafan (-0.709),  Ivancorej (0.393),  NaLLsuR (-0.164),  SemenLisenko (0.276)
Суммарная строгость судей: -0.175
Суммарная строгость участников: -0.468

Игра: okkylt, URL: https://myindie.ru/games/game/okkylt
Судьи (строгость):
Участники (строгость):  ArcasHH (0.698),  pafan (-0.709),  CreatorLynx (-0.715),  SemenLisenko (0.276)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.45

Игра: cultist-run, URL: https://myindie.ru/games/game/cultist-run
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  ArcasHH (0.698),  sasha (-0.183),  Skyline_rozan (-0.013),  GhosDist (-0.143),  pafan (-0.709),  peped (0.44),  SemenLisenko (0.276),  Heshi (-0.093),  buZZi6X (0.06),  Zarya61 (-0.625)
Суммарная строгость судей: -0.067
Суммарная строгость участников: -0.292

Игра: cult-wars, URL: https://myindie.ru/games/game/cult-wars
Судьи (строгость):
Участники (строгость):  GhosDist (-0.143),  sasha (-0.183),  KTD (-0.121),  pafan (-0.709),  Heshi (-0.093),  Zarya61 (-0.625),  buZZi6X (0.06),  SemenLisenko (0.276),  Dionis_369 (0.579)
Суммарная строгость судей: 0
Суммарная строгость участников: -0.959

Игра: a-seance, URL: https://myindie.ru/games/game/a-seance
Судьи (строгость):  Saley (0.151),  DmitriySklyarov (-0.259),  PoliKhai (-0.067)
Участники (строгость):  pafan (-0.709),  NaLLsuR (-0.164),  JantayBerikbaev (-0.227),  Ivancorej (0.393),  Tafari (-1.004),  Dionis_369 (0.579),  SemenLisenko (0.276)
Суммарная строгость судей: -0.175
Суммарная строгость участников: -0.856

Игра: cold-saratov, URL: https://myindie.ru/games/game/cold-saratov
Судьи (строгость):  Saley (0.151),  PoliKhai (-0.067),  DmitriySklyarov (-0.259)
Участники (строгость):  phanopera (0.019),  epigrodel (0.482),  ArcasHH (0.698),  dwang (-0.227),  sasha (-0.183),  pafan (-0.709),  GamerGrapes (0.031),  BobrikDobrik (0.99),  Pinecom (0.213),  buZZi6X (0.06),  SemenLisenko (0.276)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 1.65

Игра: gutsout, URL: https://myindie.ru/games/game/gutsout
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  epigrodel (0.482),  JayxK (0.299),  phanopera (0.019),  Har_On (0.347),  Skyline_rozan (-0.013),  pafan (-0.709),  BobrikDobrik (0.99),  GamerGrapes (0.031),  Tafari (-1.004),  SemenLisenko (0.276),  buZZi6X (0.06)
Суммарная строгость судей: -0.175
Суммарная строгость участников: 0.778

Игра: elementalis, URL: https://myindie.ru/games/game/elementalis
Судьи (строгость):  DmitriySklyarov (-0.259),  Saley (0.151),  PoliKhai (-0.067),  HelenAllienPoe (0.462)
Участники (строгость):  epigrodel (0.482),  dwang (-0.227),  ArcasHH (0.698),  KTD (-0.121),  BobrikDobrik (0.99),  Jil (0.912),  pafan (-0.709),  SemenLisenko (0.276)
Суммарная строгость судей: 0.287
Суммарная строгость участников: 2.301

Игра: grimuar-dyavola, URL: https://myindie.ru/games/game/grimuar-dyavola
Судьи (строгость):  PoliKhai (-0.067),  HelenAllienPoe (0.462),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  GhosDist (-0.143),  pafan (-0.709),  SemenLisenko (0.276),  GamerGrapes (0.031),  Heshi (-0.093),  buZZi6X (0.06)
Суммарная строгость судей: 0.287
Суммарная строгость участников: -0.578

Игра: v-dome-s-gulem, URL: https://myindie.ru/games/game/v-dome-s-gulem
Судьи (строгость):  PoliKhai (-0.067)
Участники (строгость):  sasha (-0.183),  JayxK (0.299),  ArcasHH (0.698),  GhosDist (-0.143),  KTD (-0.121),  SemenLisenko (0.276),  pafan (-0.709),  Ivancorej (0.393)
Суммарная строгость судей: -0.067
Суммарная строгость участников: 0.51

Игра: unity-cult_b8i, URL: https://myindie.ru/games/game/unity-cult_b8i
Судьи (строгость):  DmitriySklyarov (-0.259),  Saley (0.151),  HelenAllienPoe (0.462),  PoliKhai (-0.067)
Участники (строгость):  JayxK (0.299),  GhosDist (-0.143),  Skyline_rozan (-0.013),  pafan (-0.709),  Lacost (-0.258),  BobrikDobrik (0.99),  Tafari (-1.004),  epigrodel (0.482),  AndreyFish (0.023),  Heshi (-0.093),  ArcasHH (0.698),  buZZi6X (0.06),  Zarya61 (-0.625),  Pinecom (0.213),  Dionis_369 (0.579),  KTD (-0.121)
Суммарная строгость судей: 0.287
Суммарная строгость участников: 0.378

Игра: ne-proiznosi, URL: https://myindie.ru/games/game/ne-proiznosi
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)
Участники (строгость):  KTD (-0.121),  pafan (-0.709),  GamerGrapes (0.031),  SemenLisenko (0.276)
Суммарная строгость судей: -0.175
Суммарная строгость участников: -0.523

Игра: holy-fraud, URL: https://myindie.ru/games/game/holy-fraud
Судьи (строгость):
Участники (строгость):  phanopera (0.019),  KTD (-0.121),  SemenLisenko (0.276),  ArcasHH (0.698),  pafan (-0.709)
Суммарная строгость судей: 0
Суммарная строгость участников: 0.163

Игра: dead-channel, URL: https://myindie.ru/games/game/dead-channel
Судьи (строгость):  DmitriySklyarov (-0.259),  PoliKhai (-0.067),  Saley (0.151),  HelenAllienPoe (0.462)
Участники (строгость):  epigrodel (0.482),  dwang (-0.227),  Skyline_rozan (-0.013),  pafan (-0.709),  Ivancorej (0.393),  Zarya61 (-0.625),  ArcasHH (0.698),  YuraBulba (-0.414),  Jil (0.912),  Lacost (-0.258),  SemenLisenko (0.276),  kafel (-0.227),  Crp (0.218)
Суммарная строгость судей: 0.287
Суммарная строгость участников: 0.506

Игра: poluchi-lyubov, URL: https://myindie.ru/games/game/poluchi-lyubov
Судьи (строгость):  PoliKhai (-0.067),  Saley (0.151),  DmitriySklyarov (-0.259)